export type OpenClawAgentId =
  | "general-health"
  | "screening-specialist"
  | "care-navigator"
  | "appointment-coordinator"
  | "clinical-trial-matcher"
  | "records-specialist"
  | "medication-coach"
  | "account-manager"
  | "billing-guide"
  | "claims-refunds"
  | "provider-ops"
  | "admin-ops"
  | "treasury-operator"
  | "emergency-triage"

export type OpenClawAgentDefinition = {
  label: string
  shortLabel: string
  description: string
  functionArea: string
  prompt: string
  placeholder: string
  examples: string[]
  keywords: string[]
  modelEnv: string
  launchPrompt: string
  workflowHref: string
  workflowLabel: string
}

export const OPENCLAW_AGENT_CATALOG: Record<OpenClawAgentId, OpenClawAgentDefinition> = {
  "general-health": {
    label: "General Health Agent",
    shortLabel: "General",
    description: "General symptom and wellness guidance with clear triage escalation.",
    functionArea: "Health Questions",
    prompt:
      "You are BaseHealth's general health assistant. Provide evidence-based guidance, stay concise, and always recommend professional care for diagnosis or emergencies.",
    placeholder: "Ask a general health question...",
    examples: [
      "What are early warning signs of diabetes?",
      "How can I improve my sleep quality this week?",
      "When should I go to urgent care versus ER?",
    ],
    keywords: [
      "symptom",
      "headache",
      "fever",
      "wellness",
      "sleep",
      "nutrition",
      "exercise",
      "anxiety",
      "stress",
      "pain",
    ],
    modelEnv: "OPENCLAW_MODEL_GENERAL",
    launchPrompt: "Review my symptoms and tell me what level of care I likely need today.",
    workflowHref: "/health/dashboard",
    workflowLabel: "Open dashboard",
  },
  "screening-specialist": {
    label: "Screening Specialist",
    shortLabel: "Screening",
    description: "Personalized preventive screening guidance using USPSTF logic.",
    functionArea: "Preventive Care",
    prompt:
      "You are BaseHealth's screening specialist. Focus on preventive care and USPSTF-aligned screening recommendations based on age, sex, risk factors, and follow-up cadence.",
    placeholder: "Ask about preventive screenings...",
    examples: [
      "Which screenings should a 46-year-old get this year?",
      "How often should I get a colon cancer screening?",
      "What risk factors change mammogram frequency?",
    ],
    keywords: [
      "screening",
      "mammogram",
      "colonoscopy",
      "pap smear",
      "uspstf",
      "preventive",
      "risk factors",
      "diabetes screening",
      "cholesterol",
      "blood pressure",
    ],
    modelEnv: "OPENCLAW_MODEL_SCREENING",
    launchPrompt: "Build my preventive screening plan for the next 12 months.",
    workflowHref: "/screening",
    workflowLabel: "Start screening",
  },
  "care-navigator": {
    label: "Care Navigator",
    shortLabel: "Care",
    description: "Provider and caregiver matching plus care coordination support.",
    functionArea: "Care Matching",
    prompt:
      "You are BaseHealth's care navigator. Help users choose providers or caregivers, explain next steps, and suggest what details to prepare before visits.",
    placeholder: "Ask about finding providers or next steps...",
    examples: [
      "What specialist should I see for recurring migraines?",
      "How should I prepare for a telemedicine visit?",
      "How do I choose between urgent care and primary care?",
    ],
    keywords: [
      "provider",
      "doctor",
      "specialist",
      "caregiver",
      "appointment",
      "telemedicine",
      "find care",
      "location",
      "insurance",
      "referral",
    ],
    modelEnv: "OPENCLAW_MODEL_CARE",
    launchPrompt: "Help me find the right specialist and next booking step.",
    workflowHref: "/providers/search",
    workflowLabel: "Find providers",
  },
  "appointment-coordinator": {
    label: "Appointment Coordinator",
    shortLabel: "Appointments",
    description: "Visit preparation, scheduling logic, reminders, and follow-up plans.",
    functionArea: "Scheduling",
    prompt:
      "You are BaseHealth's appointment coordinator. Help users pick visit types, prepare for appointments, and structure follow-up tasks and reminders.",
    placeholder: "Ask about booking, prep, or follow-up timing...",
    examples: [
      "Should this be telehealth or in-person?",
      "What should I prepare before my cardiology appointment?",
      "Create a follow-up checklist after my visit.",
    ],
    keywords: [
      "schedule",
      "booking",
      "appointment",
      "calendar",
      "follow-up",
      "visit prep",
      "reschedule",
      "availability",
      "checklist",
      "reminder",
    ],
    modelEnv: "OPENCLAW_MODEL_APPOINTMENTS",
    launchPrompt: "Plan my appointment timeline including prep, visit, and follow-up.",
    workflowHref: "/appointment/book",
    workflowLabel: "Book appointment",
  },
  "clinical-trial-matcher": {
    label: "Clinical Trial Matcher",
    shortLabel: "Trials",
    description: "Trial discovery, eligibility pre-checks, and enrollment preparation.",
    functionArea: "Research Access",
    prompt:
      "You are BaseHealth's clinical trial matcher. Explain trial options, likely eligibility factors, and practical enrollment questions users should ask research sites.",
    placeholder: "Ask about trial matching or eligibility prep...",
    examples: [
      "Find trial types relevant to my condition.",
      "What questions should I ask before enrolling in a study?",
      "How do inclusion and exclusion criteria work?",
    ],
    keywords: [
      "clinical trial",
      "trial",
      "research",
      "eligibility",
      "enrollment",
      "study",
      "protocol",
      "inclusion",
      "exclusion",
      "investigator",
    ],
    modelEnv: "OPENCLAW_MODEL_TRIALS",
    launchPrompt: "Help me shortlist clinical trials and prepare eligibility questions.",
    workflowHref: "/clinical-trials",
    workflowLabel: "Browse trials",
  },
  "records-specialist": {
    label: "Medical Records Specialist",
    shortLabel: "Records",
    description: "Medical record organization, exports, summaries, and privacy-safe sharing guidance.",
    functionArea: "Medical Records",
    prompt:
      "You are BaseHealth's medical records specialist. Help users organize, summarize, and export their medical information while minimizing sensitive data exposure. Provide practical steps and checklist-style guidance.",
    placeholder: "Ask about importing, exporting, or summarizing records...",
    examples: [
      "Help me create a one-page medical history summary for a new doctor.",
      "What should I include in an ER-ready medication and allergy list?",
      "How do I export my records and share them securely?",
    ],
    keywords: [
      "medical records",
      "records",
      "export",
      "summary",
      "allergies",
      "immunizations",
      "lab results",
      "privacy",
      "hipaa",
      "share",
    ],
    modelEnv: "OPENCLAW_MODEL_RECORDS",
    launchPrompt: "Help me build a clean medical summary (conditions, meds, allergies, key labs) for a new provider.",
    workflowHref: "/medical-records",
    workflowLabel: "Open records",
  },
  "medication-coach": {
    label: "Medication Coach",
    shortLabel: "Meds",
    description: "Medication reminders, adherence plans, and safety-first interaction questions for your clinician.",
    functionArea: "Medication Management",
    prompt:
      "You are BaseHealth's medication coach. Help users manage medication schedules and prepare safety questions for clinicians. Do not prescribe or diagnose; emphasize contacting a pharmacist or clinician for interaction questions.",
    placeholder: "Ask about medication schedules or adherence...",
    examples: [
      "Create a daily schedule for my meds with meal timing.",
      "What questions should I ask about side effects and interactions?",
      "Help me set up a simple refill and reminder plan.",
    ],
    keywords: [
      "medication",
      "meds",
      "refill",
      "dose",
      "schedule",
      "side effects",
      "interaction",
      "pharmacy",
      "adherence",
      "reminder",
    ],
    modelEnv: "OPENCLAW_MODEL_MEDICATION",
    launchPrompt: "Build a simple, safe medication schedule and reminder plan for me (include meal timing and refills).",
    workflowHref: "/medication",
    workflowLabel: "Open meds",
  },
  "account-manager": {
    label: "Account Manager",
    shortLabel: "Account",
    description: "Sign-in support, profile maintenance, and account settings guidance.",
    functionArea: "Account Management",
    prompt:
      "You are BaseHealth's account manager. Guide users through sign-in, security basics, profile updates, and account settings without requesting sensitive secrets.",
    placeholder: "Ask about sign-in, profile, or account settings...",
    examples: [
      "How do I connect my wallet to my account?",
      "What should I update in my profile before booking care?",
      "How do I check if my Base sign-in setup is complete?",
    ],
    keywords: [
      "account",
      "sign in",
      "login",
      "profile",
      "settings",
      "wallet login",
      "privy",
      "security",
      "session",
      "identity",
    ],
    modelEnv: "OPENCLAW_MODEL_ACCOUNT",
    launchPrompt: "Audit my account setup and list anything missing for Base sign-in.",
    workflowHref: "/settings",
    workflowLabel: "Open settings",
  },
  "billing-guide": {
    label: "Billing Guide",
    shortLabel: "Billing",
    description: "Payment and Base blockchain transaction explanation with transparency.",
    functionArea: "Payments",
    prompt:
      "You are BaseHealth's billing guide. Explain healthcare payments, wallet transactions, and Base network settlement in plain language while preserving privacy.",
    placeholder: "Ask about payments, wallets, and transaction details...",
    examples: [
      "How do BaseHealth payments work on Base blockchain?",
      "What does this transaction hash mean for my appointment payment?",
      "How can I verify a USDC payment was settled?",
    ],
    keywords: [
      "payment",
      "billing",
      "wallet",
      "base",
      "blockchain",
      "usdc",
      "transaction",
      "gas",
      "invoice",
      "receipt",
    ],
    modelEnv: "OPENCLAW_MODEL_BILLING",
    launchPrompt: "Show me how to verify my payment receipt and transaction status.",
    workflowHref: "/billing",
    workflowLabel: "Open billing",
  },
  "claims-refunds": {
    label: "Claims & Refunds Agent",
    shortLabel: "Refunds",
    description: "Refund eligibility, claim status, receipts, and audit trail support.",
    functionArea: "Refund Operations",
    prompt:
      "You are BaseHealth's claims and refunds specialist. Help users understand refund outcomes, required details, and expected processing timelines while staying factual and transparent.",
    placeholder: "Ask about refunds, receipts, or payment issue resolution...",
    examples: [
      "How do I check if my refund was processed?",
      "What information is needed for a refund request?",
      "Where can I view my refund transaction on BaseScan?",
    ],
    keywords: [
      "refund",
      "claim",
      "chargeback",
      "dispute",
      "receipt",
      "billing issue",
      "reversal",
      "payment failed",
      "refund status",
      "basescan",
    ],
    modelEnv: "OPENCLAW_MODEL_REFUNDS",
    launchPrompt: "Check what I need to track a refund and confirm payout status.",
    workflowHref: "/admin/bookings",
    workflowLabel: "Open refund ops",
  },
  "provider-ops": {
    label: "Provider Ops Agent",
    shortLabel: "Provider",
    description: "Provider onboarding, credential verification, attestations, payouts, and practice setup guidance.",
    functionArea: "Provider Operations",
    prompt:
      "You are BaseHealth's provider operations agent. Help providers complete onboarding, understand verification steps, configure payout wallets, and follow compliance-friendly workflows. Do not request private keys or secrets.",
    placeholder: "Ask about provider onboarding, verification, or payouts...",
    examples: [
      "What do I need to finish provider onboarding and get approved?",
      "How do attestations work for provider credentials on Base?",
      "Help me configure a payout wallet for USDC.",
    ],
    keywords: [
      "provider",
      "onboarding",
      "npi",
      "license",
      "verification",
      "attestation",
      "payout",
      "usdc",
      "practice",
      "dashboard",
    ],
    modelEnv: "OPENCLAW_MODEL_PROVIDER_OPS",
    launchPrompt: "Audit my provider onboarding checklist and tell me what is missing to get approved.",
    workflowHref: "/provider/dashboard",
    workflowLabel: "Open provider hub",
  },
  "admin-ops": {
    label: "Admin Ops Agent",
    shortLabel: "Admin",
    description: "Operational support for reviews, bookings, refunds, compliance checklists, and incident triage.",
    functionArea: "Operations",
    prompt:
      "You are BaseHealth's admin operations agent. Help admins run reviews, handle booking exceptions, and keep billing/refund workflows consistent. Prioritize clear checklists and auditability.",
    placeholder: "Ask about operations, reviews, and refunds...",
    examples: [
      "Walk me through processing a refund with a proper audit trail.",
      "What are the steps to review and approve a provider application?",
      "Help me triage a payment dispute and gather the right info.",
    ],
    keywords: [
      "admin",
      "operations",
      "refund",
      "review",
      "application",
      "audit",
      "compliance",
      "incident",
      "triage",
      "ops",
    ],
    modelEnv: "OPENCLAW_MODEL_ADMIN_OPS",
    launchPrompt: "Give me an ops checklist for refunds and booking exceptions (including what to record for audit).",
    workflowHref: "/admin",
    workflowLabel: "Open admin",
  },
  "treasury-operator": {
    label: "Treasury Operator",
    shortLabel: "Treasury",
    description: "Treasury balance checks, settlement operations, refunds/payout planning, and key-management hygiene.",
    functionArea: "Treasury",
    prompt:
      "You are BaseHealth's treasury operator agent. Help manage Base USDC treasury operations, reconcile receipts, and plan refunds/payouts safely. Do not request private keys or secrets; recommend hardware wallets and proper access controls.",
    placeholder: "Ask about treasury balances, payouts, or refunds...",
    examples: [
      "How do I reconcile Base Pay receipts with treasury balances?",
      "What is a safe operational flow for refunds using the treasury wallet?",
      "How should I store and rotate secrets for production?",
    ],
    keywords: [
      "treasury",
      "settlement",
      "usdc",
      "balance",
      "refund",
      "payout",
      "reconcile",
      "wallet",
      "security",
      "basescan",
    ],
    modelEnv: "OPENCLAW_MODEL_TREASURY",
    launchPrompt: "Help me set up a safe treasury ops workflow for Base USDC (receipts, refunds, payouts, audit trail).",
    workflowHref: "/treasury",
    workflowLabel: "Open treasury",
  },
  "emergency-triage": {
    label: "Emergency Triage Agent",
    shortLabel: "Emergency",
    description: "Fast symptom triage guidance focused on when to call 911 / ER / urgent care.",
    functionArea: "Emergency",
    prompt:
      "You are BaseHealth's emergency triage agent. Keep responses short, prioritize safety, and recommend emergency services when red flags are present. Do not provide definitive diagnoses.",
    placeholder: "Describe symptoms for urgent guidance...",
    examples: [
      "Chest pain with shortness of breath: what should I do?",
      "Signs of stroke to watch for right now?",
      "High fever and confusion: ER or urgent care?",
    ],
    keywords: [
      "emergency",
      "triage",
      "chest pain",
      "stroke",
      "shortness of breath",
      "bleeding",
      "poisoning",
      "seizure",
      "911",
      "er",
    ],
    modelEnv: "OPENCLAW_MODEL_EMERGENCY",
    launchPrompt: "Triage my symptoms and tell me whether to call 911, go to ER, or schedule urgent care (include red flags).",
    workflowHref: "/emergency",
    workflowLabel: "Open emergency",
  },
}

export const OPENCLAW_AGENT_IDS = Object.keys(OPENCLAW_AGENT_CATALOG) as OpenClawAgentId[]

const OPENCLAW_AGENT_ALIASES: Record<string, OpenClawAgentId> = {
  "general-health": "general-health",
  general: "general-health",
  health: "general-health",
  "health-assistant": "general-health",
  "screening-specialist": "screening-specialist",
  screening: "screening-specialist",
  preventive: "screening-specialist",
  "care-navigator": "care-navigator",
  care: "care-navigator",
  provider: "care-navigator",
  caregiver: "care-navigator",
  "appointment-coordinator": "appointment-coordinator",
  appointments: "appointment-coordinator",
  scheduling: "appointment-coordinator",
  "clinical-trial-matcher": "clinical-trial-matcher",
  trials: "clinical-trial-matcher",
  trial: "clinical-trial-matcher",
  "records-specialist": "records-specialist",
  records: "records-specialist",
  "medical-records": "records-specialist",
  "medication-coach": "medication-coach",
  meds: "medication-coach",
  medication: "medication-coach",
  "account-manager": "account-manager",
  account: "account-manager",
  signin: "account-manager",
  "sign-in": "account-manager",
  "billing-guide": "billing-guide",
  billing: "billing-guide",
  payments: "billing-guide",
  blockchain: "billing-guide",
  "claims-refunds": "claims-refunds",
  refunds: "claims-refunds",
  refund: "claims-refunds",
  claims: "claims-refunds",
  "provider-ops": "provider-ops",
  "provider-operations": "provider-ops",
  "admin-ops": "admin-ops",
  ops: "admin-ops",
  treasury: "treasury-operator",
  "treasury-operator": "treasury-operator",
  emergency: "emergency-triage",
  "emergency-triage": "emergency-triage",
}

export function normalizeOpenClawAgent(input?: string | null): OpenClawAgentId | null {
  if (!input) return null
  const normalized = input.toLowerCase().trim()
  return OPENCLAW_AGENT_ALIASES[normalized] || null
}
